version: 2

models:
  - name: d__accounts
    description: "Table containing basic account information on opportunities and leads. Account records are created after leads are converted."
    columns:
      - name: account_id
        description: "Primary key taken directly from the original seed file."
        tests:
          - unique
          - not_null
      - name: account_company
        description: "The company associated with the account_id.  There should not be duplicate company names in this dataset.  If so talk to team X."
        tests:
          - unique
          - not_null
      - name: account_country
        description: "country associated with the account."
        tests:
          - accepted_values:
              values: ['US']
      - name: account_state
        description: "state associated with the account."
      - name: account_city
        description: "city associated with the account."
      - name: primary_contact_first_name
        description: "first name associated with the primary contact."
      - name: primary_contact_last_name
        description: "last name associated with the primary contact."
      - name: primary_contact_job_title
        description: "job titlee associated with the primary contact."
      - name:  primary_contact_email
        description: "email associated with the primary contact."
      - name: account_industry
        description: "industry associated with the account."
      - name: account_fleet_size
        description: fleet size associated with the account."
      - name: lead_created_at_date
        description: "date of when the lead was created."
      - name: lead_converted_at_date
        description: "date of when the lead was converted."
      - name: lead_source
        description: "source the lead came from."
      - name: opportunity_created_at_date
        description: "date of when the opportunity was created."
      - name: opportunity_closed_at_date
        description: "date of when the opportunity was closed."
      - name: opportunity_is_closed
        description: "true of the opportunity is closed. This field should never be null."
        tests:
          - not_null
          - accepted_values:
              values: ['TRUE', 'FALSE']
      - name: opportunity_is_won
        description: "true of the opportunity is won.  This field should never be null."
        tests:
          - not_null
          - accepted_values:
              values: ['TRUE', 'FALSE']
  - name: d__leads
      description: "Leads are created from various sources.  When leads are converted contact, account and opportunity records are created."
        - name: lead_id
          description: "Primary key, one row is one lead."
          tests:
            - unique
            - not_null
        - name: lead_first_name
          description: "first name associated with the lead."
          tests:
            - not_null
        - name: lead_last_name
          description: "last name associated with the lead."
          tests:
            - not_null
        - name: lead_job_title
          description: "job title associated with the lead."
        - name: lead_email
          description: "email associated with the lead."
        - name: lead_company
          description: "The company associated with the lead.  There should not be duplicate company names in this dataset.  If so talk to team X."
          tests:
            - unique
            - not_null
        - name: lead_created_at_date
          description: "date of when the lead was created."
        - name: lead_converted_at_date
          description: "date of when the lead was converted."
        - name: lead_source
          description: "source the lead came from."
        - name: lead_country
          description: "country associated with the lead."
          tests:
            - accepted_values:
                values: ['US']
        - name: lead_city
          description: "city associated with the lead."
        - name: lead_state
          description: "state associated with the lead."
        - name: lead_industry
          description: "industry associated with the lead."
        - name: lead_fleet_size
          description: "fleet size associated with the lead."
        - name: opportunity_status
          description: Current status of the opportunity that the lead created (if converted).  See acceptable value list for categories."
          tests:
            - accepted_values:
                values: ['won opportunity', 'lost opportunity', 'open opportunity', 'lead not converted to opportunity']



  - name: fct_leads_daily

