version: 2

models:
  - name: stg_accounts
    description: "Accounts are created after leads have converted. Owned by the sales and marketing team."
    columns:
      - name: account_id
        description: "Primary key taken directly from the original seed file."
        tests:
          - unique
          - not_null
      - name: account_company
        description: "The company associated with the account_id.  There should not be duplicate company names in this dataset.  If so talk to team X."
        tests:
          - unique
          - not_null
      - name: primary_contact_id
        description: "FK to stg_contacts.id"
        tests:
          - relationships:
              to: ref('stg_contacts')
              field: contact_id
      - name: account_country
        description: "country associated with the account."
        tests:
          - accepted_values:
              values: ['US']
      - name: account_state
        description: "state associated with the account."
      - name: account_city
        description: "city associated with the account."
      - name: account_industry
        description: "industry associated with the account."
      - name: account_fleet_size
        description: fleet size associated with the account."
  - name: stg_contacts
    description: "Contact records are created after leads have converted. Owned by the sales and marketing team."
    columns:
      - name: contact_id
        description: "Primary key taken directly from the original seed file."
        tests:
          - unique
          - not_null
      - name: contact_first_name
        description: "first name associated with the contact."
        tests:
          - not_null
      - name: contact_last_name
        description: "last name associated with the contact."
        tests:
          - not_null
      - name: contact_job_title
        description: "job title associated with the contact."
      - name: contact_email
        description: "email associated with the contact."
      - name: account_id
        description: "account_id associated with the contact."
        tests:
          - relationships:
              to: ref('stg_accounts')
              field: account_id
      - name: lead_id
        description: "lead_id associated with the contact."
        tests:
          - relationships:
              to: ref('stg_leads')
              field: lead_id
      - name: contact_created_at
        description: "timestamp of when the contact was created."
      - name: contact_created_at_date
        description: "date of when the contact was created."
  - name: stg_leads
    description: "Created automatically from various sources. Owned by the sales and marketing team."
    columns:
      - name: lead_id
        description: "Primary key taken directly from the original seed file."
        tests:
          - unique
          - not_null
      - name: lead_first_name
        description: "first name associated with the lead."
        tests:
          - not_null
      - name: lead_last_name
        description: "last name associated with the lead."
        tests:
          - not_null
      - name: lead_job_title
        description: "job title associated with the lead."
      - name: lead_email
        description: "email associated with the lead."
      - name: lead_company
        description: "The company associated with the lead.  There should not be duplicate company names in this dataset.  If so talk to team X."
        tests:
          - unique
          - not_null
      - name: lead_created_at
        description: "timestamp of when the lead was created."
      - name: lead_created_at_date
        description: "date of when the lead was created."
      - name: lead_converted_at
        description: "timestamp of when the lead was converted."
      - name: lead_converted_at_date
        description: "date of when the lead was converted."
      - name: lead_source
        description: "source the lead came from."
      - name: lead_country
        description: "country associated with the lead."
        tests:
          - accepted_values:
              values: ['US']
      - name: lead_city
        description: "city associated with the lead."
      - name: lead_state
        description: "state associated with the lead."
      - name: lead_industry
        description: "industry associated with the lead."
      - name: lead_fleet_size
        description: fleet size associated with the lead."
  - name: stg_opportunities
    description: "Opportunities are created after leads have converted. Owned by the sales and marketing team."
    columns:
      - name: opportunity_id
        description: "Primary key taken directly from the original seed file."
        tests:
          - unique
          - not_null
      - name: account_id
        description: "account_id associated with the opportunity."
        tests:
          - relationships:
              to: ref('stg_accounts')
              field: account_id
      - name: opportunity_created_at
        description: "timestamp of when the opportunity was created."
      - name: opportunity_created_at_date
        description: "date of when the opportunity was created."
      - name: opportunity_closed_at
        description: "timestamps of when the opportunity was closed."
      - name: opportunity_closed_at_date
        description: "date of when the opportunity was closed."
      - name: opportunity_is_closed
        description: "true of the opportunity is closed. This field should never be null."
        tests:
          - not_null
          - accepted_values:
              values: ['TRUE', 'FALSE']
      - name: opportunity_is_won
        description: "true of the opportunity is won.  This field should never be null."
        tests:
          - not_null
          - accepted_values:
              values: ['TRUE', 'FALSE']
      - name: opportunity_country
        description: "country associated with the opportunity."
        tests:
          - accepted_values:
              values: ['US']
      - name: opportunity_state
        description: "state associated with the opportunity."
      - name: opportunity_city
        description: "city associated with the opportunity."